version: "3.8"
services:
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:80001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENBALED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
networks:
  default:
    name: catalog-network
    external: true